repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: rabbitmq
    namespace: default
    chart: bitnami/rabbitmq
    version: ~11.13.0
    labels:
      tools: rabbitmq
    wait: true
    secrets:
      - rabbitmq-secret.yaml.enc

  
  
  