repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: kitabisa
    url: https://chart.kitabi.se
    username: rider
    password: H2m5A4a5bHmY5jG6


releases:
  - name: rabbitmq
    namespace: default
    chart: bitnami/rabbitmq
    version: ~11.13.0
    labels:
      tools: rabbitmq
    wait: true
    secrets:
      - stg/rabbitmq-secret.yaml.enc

  - name: nginx
    namespace: default
    chart: bitnami/nginx
    version: ~15.1.0
    labels:
      tools: nginx
    wait: true
    values:
      - stg/nginx.yaml

  - name: server
    namespace: default
    chart: kitabisa/app
    version: 0.17.8-alpha.4
    labels:
      tools: server
    wait: true
    values:
      - stg/server.yaml

  

  
  