repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: kitabisa
    url: https://chart.kitabi.se
    username: rider
    password: H2m5A4a5bHmY5jG6

releases:
  - name: {{ requiredEnv "APP_NAME" }}-redis-{{ requiredEnv "ENV" }}
    namespace: default
    chart: bitnami/redis
    version: ~11.13.0
    wait: true
    values:
      - {{ requiredEnv "ENV" }}/redis.yaml

  - name: {{ requiredEnv "APP_NAME" }}-nginx-{{ requiredEnv "ENV" }}
    namespace: default
    chart: bitnami/nginx
    version: ~15.1.0
    labels:
      tools: nginx
    wait: true
    values:
      - {{ requiredEnv "ENV" }}/nginx.yaml

  - name: {{ requiredEnv "APP_NAME" }}-server-{{ requiredEnv "ENV" }}
    namespace: default
    chart: kitabisa/app
    version: 0.17.8-alpha.4
    labels:
      tools: server
    wait: true
    values:
      - {{ requiredEnv "ENV" }}/server.yaml
      - values.yaml.gotmpl
      - volume.yaml

  - name: {{ requiredEnv "APP_NAME" }}-config-{{ requiredEnv "ENV" }}
    namespace: default
    chart: kitabisa/config
    version: ~0.4.0
    values:
      - values.yaml.gotmpl
    secrets:
      - {{ requiredEnv "ENV" }}/config.yaml