config:
    enabled: ENC[AES256_GCM,data:zWqaVg==,iv:m274mp2BZkv99uqghxLy63xJj8LTH6Z27u6qlRnMWxA=,tag:tf78x0G/1vplgjwsvSzRCw==,type:bool]
    data:
        #ENC[AES256_GCM,data:8foSmA==,iv:BxPWabQwOoNaLR+A/jI8bWLRIUlznaHnBm9hLb1GnBk=,tag:YTkQkKQLJd1ArSrZs8YtVA==,type:comment]
        APP_HOST: ENC[AES256_GCM,data:dYFLGHe1aA==,iv:ZR2JqbRn92yzLwCDh9EOSysKluJskPsLPHHoYhsrLS4=,tag:iNWYQnLZivMeXIpsbVQWog==,type:str]
        APP_PORT: ENC[AES256_GCM,data:dXrIEA==,iv:l6przicVMF/N5NFHnYCjahlKgV5uXPWiV2oonAKmDLY=,tag:NWwP+5X2o+d56pQ3u39iFA==,type:str]
        APP_NAME: ENC[AES256_GCM,data:TZaiJg==,iv:vsylyUB8WOVFyCh8RH5UeoA2qHKWRQiRFCxxtJADnvk=,tag:YiHAL6Qf8mOazYLRkxbqbQ==,type:str]
        APP_DEBUG: ENC[AES256_GCM,data:SW7bVw==,iv:K45Hy6SrSRWAY9mB3MyL9wvczqflKoAjvufCZjWGKUU=,tag:hPxSvzPccAXcb74wFHhYcQ==,type:str]
        APP_LOG_PRETTY: ENC[AES256_GCM,data:SqPyDQ==,iv:l776d2DE5MUmgOgrcGX9qm4KAkdgBD/y4tl2AN2akYw=,tag:m7WK+ut6wx8g0/rfst/L2g==,type:str]
        APP_LOG_LEVEL: ENC[AES256_GCM,data:BUL0MQ==,iv:JJt5Wz8e5/d4CXHv6ApPQDxvmaMgv8HBu+WjBXXnr7M=,tag:SzOq8gveFBKdGlFMGli+8A==,type:str]
        GENERATE_FROM: ENC[AES256_GCM,data:3Q0hAGzNSVMVXZ+V,iv:Ras9JtdMTTQU7fpYhky4sr2FD+c+OIxNCpeD/NdLi/A=,tag:v+Y5Dx9oZXr03uIRTzlNjw==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1turq833hg3958lwfa20qmmhgddewp265jzc9hkqzzylzgqcw8umsdvnhtj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q1VLcXZqN1kwTTRQZWpq
            U2ptSE5qNWtqQWNyb1V0L0hoQVA2bEFPaENjCm80aG1vNWxkNVhLbEhKcHNnYlNM
            QWlQYVJEM0F4TWFxVWtLdWlGWW1xQ3cKLS0tIFl6angvc2NmL0JINDJzeWN6UHUx
            TE85SkxvbUJ4dXh1TVprTE8wR21FVHcKOMyhH6D5MDyJGKyDPH+72Z8rQBp4KWsW
            EHTENj3k5bDg+yQYP6wqfrCX4e4RGIzZea0RBS0RlXaDehlw/mjvDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T08:12:18Z"
    mac: ENC[AES256_GCM,data:bkOxOYz/EBz1DeKbYytUUqnmjZQPqNesyGypdzckSRrWVgawNTSuiFtVxJ9B7TO6G4MFwGCMigMpfQTzHoGBMIR9m1u3GaTRWo8ZZ0k1hzd1eQdQTq4PKqzjQUwyvoDNN7nSidLeXZAjb/xavR9X1LdqHF48jbpQNJmOqyjPjjA=,iv:UVNNaYP5qusT22MbJv4Pv9nJXkFAZJGPaEApclS+3os=,tag:CcPs7eZ4btndFm8FsrWypw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3