sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1turq833hg3958lwfa20qmmhgddewp265jzc9hkqzzylzgqcw8umsdvnhtj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRzBrQVQ4N0EwcjR4a215
            WFhYelhXZU5rTEU0VVRZUmZVQjBvUXBNbEdFCm1KdUpWdkdibHdHV0tkL1RiRzlp
            TG9hbnNxS21rVTRiWDk1V3pWRXl5SW8KLS0tIFQ3MUE3RExRbEpzWXdkL1JVV2Nl
            WjB1UE5XcnVyOGZUbnpNV3JjUFNaWGsK/6sUKfzxwXKld+H4x8cwltzotdLRLPAP
            FCM6Q8UlOvO3wtFVs8dKzUfyuR6YmXOE2tLqm524wIIgxUqyrahEwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T09:56:36Z"
    mac: ENC[AES256_GCM,data:tEliLti9y4eSVY7Cc1o1Z5x8IPYpJG38LIUMgM6lDz9tseV9HrcDSLq2VPiRLuskwnookIjZZtmj+7tTCJ7nOKiKg40C2wtR97rN3cG5DdXNM58eNhZkdMyYzk82ZuUM1uMmlmz2WfBU/I0kptR/x5ZZszXirqJInLbFjAloxmE=,iv:zoO06kuJYFigP44k4/heEG5r0gaGmChYEGW5f4L+XFw=,tag:0CxX31koK8K3qs5l1NILMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3