replicaCount: ENC[AES256_GCM,data:Gw==,iv:0hUQwTFy996jHM80HcVm7tLeK5Uo8pwGwvWYx8r9+h0=,tag:F2BQBvCIN6PtID/l+zyMlA==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-12T06:04:13Z"
    mac: ENC[AES256_GCM,data:cVicvRvFkRibz2GMonBULFkd4gVjA22PbmxPG98iGBOA+NeGmQ6ph3O+1dw39zsR03e32/sj/COChMZn20MdO2hdhaYTbgbn3Qed3dRtdJ+poDTqiCx+sf9Xr0TuYvavKPxPXP+te0ufSALm67UuL223uH+SPkJjy4V4oSlkUAQ=,iv:Ff2MjU7UbtVPdF5OesP1mgk8JgH+QwEkNifcAINrVvU=,tag:wKSsjRpD/wiTFXMgaiZ3XQ==,type:str]
    pgp:
        - created_at: "2023-07-12T06:04:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8d12Cv3hM/4AQ/+J7dBuQWz4OWmfCLAwvJlrMF1I0pGdJG9uQ8MzRJ7aDy6
            XJiYbt/DZNOBHLJC6XylPmuHR90mSNtQvu5kfWc+wt0GOXQzsGIQaMQ45O/wYF9X
            1jpYwLL0v9TB/hvv+R+GwWSa4/apdgk8D4SCgCLiEqdeyQN9D6rzYiJP8okRQ02T
            rF8YLIkJzklXi6I7NrLhFbz0yy01lPXKzdqH3VgJxX/1/H1s0Qpj2tisiVApM7wb
            FtqeVpr3KRfvEjFHdzXHs1kHse0bAS/0caCh6bGBOUWL/KpJ3y8bZIItSS8xK0D8
            m7sdjahVrKkQFkqPfgwQg5soajhoNtknrXS7SC8vwjrZYgfXroQ7O7Z4ucVSfRXz
            evaV2NzCe/wMLLn6caKgb8N4OXaSeFCiK9Y7NVRXh0Vpl4yHXVRjlRV/cOMLippi
            6EY3wEtiMYknNXtXn6zNaPv9qNTaqZ+r5DnVn81zv5ZfO+8Kpo8ZzczWvVTJ8pHX
            RpKSq/nfHhWjTwQIuAXYqixumC629XHyjW48tkZZaVO9KKjsk/UHqYtpFvt6FBTy
            j8xpHK+iceqC3F3f1Qjj/Lj8xANIal9jg8QN5hTLu38WnJkSzVa3DYdkV4D2JKkl
            ISWzSe2yv9Ejg+RFtaBbkZY0S//4aq6OWUhAsNDYurfCyJ7ynQ+V1Smi46tW3OvU
            aAEJAhCibq3soJSG5ws357OcLhSC5MAU++QSHpIsXnExFImYoFpZkdJ60d55t93V
            jePEt683isto2WNSMOUteuY/Xh0tDoCo54Enocau3o6HZT3TJqHQZh2+hqySkhCC
            OUk6uQtb4UxI
            =zck3
            -----END PGP MESSAGE-----
          fp: 3CE2092F5517FDD551FC6D400EAD4BCD857A91F1
    unencrypted_suffix: _unencrypted
    version: 3.7.3