apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fx-nginx
  namespace: flux-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: '15.1.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-demo
      interval: 1m
  values:
    replicaCount: 1
  valuesFrom:
  - kind: ConfigMap
    name: prod-env-values
    valuesKey: "./repository/helmRelease/values-secret.yaml"