apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fx-nginx
  namespace: flux-demo
spec:
  interval: 1m
  chart:
    spec:
      chart: bitnami/nginx
      version: '15.1.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami-repository
        namespace: flux-demo
      interval: 1m
  values:
    replicaCount: 1