apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fx-redis
  namespace: flux-demo
spec:
  interval: 1m
  chart:
    spec:
      chart: bitnami/redis
      version: '17.11.8'
      sourceRef:
        kind: HelmRepository
        name: bitnami-repository
        namespace: flux-demo
      interval: 1m
  values:
    architecture: standalone 
    master:
      persistence:
        enabled: false