apiVersion: v1
kind: Secret
metadata:
    name: flux-secret
data:
    CITY: ENC[AES256_GCM,data:hXmaKgCYptjhY4yS,iv:lqC8wjsepbnYDxQiGXcXbeMImYxFpUf2RHvBgw48meg=,tag:DZ7ALWOPhkZS+EtSBXgY0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-12T16:33:59Z"
    mac: ENC[AES256_GCM,data:9PDjkUXnTZauHG8rQGEFC5ZvEA7/XxlckZNUeIHxVzmpS7b90Yml7jlOnxVIkI2g0f9MEADvT58Ith4so3xsUneskVVtAYH/OIsmquP6ylHg1Rz27VQ6CE3wFClyrDqdkIwwCmhqk3Ti1Qnp7ALXSwyUnBfCmeNgFwM0ZA1xtXY=,iv:MCt9FQ6Bvmijx/vASbr8LTApw7E6eP3qJBHauivUHak=,tag:XbDEhFYXXm30WUPYGzIcyg==,type:str]
    pgp:
        - created_at: "2023-07-12T16:33:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+raoDloWAc8AQ//c0D5ZPc/XiwL02eXahvLCCnDN2udvFymADvUmzNg9qdw
            ImNbWdFFByrHpj12QMFQHaIApYo/iwXX55fm1ykqhEqsYwNeMrbvUw6qAd3y2hC2
            GwsNs1V1qk2zmhjb0kosekOhdFtLZDo6J7E+ewS4BTYUefhlJB6zFhdQfiuJMhF3
            UW0hP6FsvPB1bOdWtoMQ2Ye2K0bvHdbeRqDD9sWZhBcaSQz6vsewp6MtXVdXRzfq
            u8PZqy0+Orf8yaqsnKctjllVFrB6c31ewuOGna0yarKgQZLJKntRXxoX4IviLHKm
            +T0a0Ydt7igJGG+oipqDkCjpcRnOSSKp0KybpTdfD2rKwFnQG49D7ycbmQEm9F92
            oH6GWrlKH/CZOhh42VMG90hfVO/jHmCewgjOfqnlqzKIPGwuDo0WjgGQF262bJTO
            lRAM7ki3kKk3qGGk3WiNlPdLlNelSC6k0AIN29RgZMdYbaLBvqe/a5/9/oYMLPns
            niOeb1IXZt+0NItnRK0VVHABHyfOoMbx/heZ4i9cJ0mnKLQlUmoE36ZQCQkfwAq7
            Z+KbhayxMZFItOSf8qZQoR6FFaAF5CPjojOyw+p7fVLRvFX+62IUUAoU40X/yGPb
            ZRXRMBkB/bpAb0Z8+n2sNnbM1Codah8NxkyMrhO/d8HbRGMtATUyHS5C/eUXZuvU
            aAEJAhDNewcwGP0QeIxG2tTg0ywU9iI9eS9ZFVI6uBDTYiDl9/iw5uhVLF/VXuYI
            Km1MIZhL7+prYlx+D5r97a6vFz765NMNfMslVwYU+CUnSlNeY/HXJTFiPwU7vqJW
            HV/Xnh+PbWZn
            =UaDH
            -----END PGP MESSAGE-----
          fp: BA568E0BE2D8970761067E870CAD9ED30F71B1BE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3